
###########
# BUILDER #
###########

# pull official base image
FROM python:3.9-slim-buster AS builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# install psycopg2 dependencies
RUN apt-get update \
    && apt-get install -yyq  libpq-dev gcc 



# lint
RUN pip install --upgrade pip
RUN pip install flake8==3.9.2
COPY . .


# install dependencies
COPY ./requirements.txt .
RUN flake8 --ignore=E501,F401 ./Host_Pathogen_Interaction
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt


#########
# FINAL #
#########

# pull official base image
FROM python:3.9-slim-buster

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system app -ingroup app


# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME


# install dependencies
RUN apt-get update && apt-get -y install netcat libpq5 
RUN dpkg -L netcat 
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --no-cache /wheels/*

# copy entrypoint_prod.sh
COPY ./entrypoint_prod.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint_prod.sh
RUN chmod +x  $APP_HOME/entrypoint_prod.sh



# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run entrypoint_prod.sh
ENTRYPOINT ["/home/app/web/entrypoint_prod.sh"]
