# Generated by Django 4.0.2 on 2022-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0011_alter_csvfile_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='fileType',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
